from app.services.detector import get_detector, SignLanguageDetector
from app.services.video_processor import process_video_frame_by_frame, convert_avi_to_mp4, stream_video_file
from app.services.sentence_generator import generate_sentence_from_detections
from app.services.paraphraser import get_paraphraser